
# subimage. Index of first time sample
Tstart: 1000

# Size of image to extract 
M0: 100 # number of rows
N0: 100 # number of cols

# Image parameters
folder: "./dependencies/measurementData"
file: "BalderRIR.mat"
room: "Balder"

sampling:
  dx: 0.03
  fs: 11250
  cs: 340