defaults:
  - /dicts@BS : BS_tan
  - /database: Balder_T0_M100
  - _self_

saving_param:
  folder: saved_dicts/tan_dicts
  file: BS_m_${BS.M}_n_${BS.N}_vsc_${BS.n_v_scales}_hsc_${BS.n_h_scales}_bases_${BS.base_v}_${BS.base_h}_thV_${BS.n_v_thetas}_thH_${BS.n_h_thetas}.mat


BS:
  sampling: ${database.sampling}

# or
# 
# BS:
#   sampling:
#     dx: 3e-2
#     fs: 11250
#     cs: 340 
