defaults:
  - _self_
  - boost_sys
  - images
  - ista

output_dir: ${hydra:runtime.output_dir}

outputs:
  images:
    # Output for saved images
    folder: ${output_dir}/images
    file_im: reconstructed_image.png
    file_mat: images.mat
    f_write_dict: True

  performance:
    folder: ${output_dir}/performance
    file: perform.mat
    f_write_dict: True

# indexes of the dict Sk to remove
rm_sk_ids:
  - 2
  - 4